name: Daily update 0050 charts

on:
  schedule:
    # 18:30 Asia/Taipei = 10:30 UTC
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yfinance pandas plotly

      - name: Generate charts
        run: python scripts/make_charts.py

      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name  "github-actions[bot]"
          git add 0050_*.html
          git commit -m \"chore: update charts $(date -u +'%Y-%m-%d')\" || echo \"No changes\"
          git push https://$GH_TOKEN@github.com/${{ github.repository }}.git gh-pages
