- name: Checkout default branch
  uses: actions/checkout@v4
  with:
    persist-credentials: false   # push 時再手動加 PAT

# …產生圖表…

- name: Commit & push to gh-pages
  env:
    GH_TOKEN: ${{ secrets.GH_PAT }}
  run: |
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git config user.name  "github-actions[bot]"

    # 第一次跑時 main 還在；改切孤兒 gh-pages 分支
    git switch --orphan gh-pages
    git rm -rf .
    mv ../0050_*.html .
    git add 0050_*.html
    git commit -m "chore: init gh-pages $(date -u +'%Y-%m-%d')"

    git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git"
    git push -u origin gh-pages
